dist: trusty
sudo: false
language: php
php:
- 7.2
- 7.3
env:
  global:
  - WP_VERSION=latest WP_MULTISITE=0
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
cache:
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
install:
- nvm install 12
- npm install
- npm rebuild node-sass
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
before_deploy:
- npm run zip
- ls -la snow-monkey-the-events-calendar-support.zip
- export RELEASE_FILE=$(ls snow-monkey-the-events-calendar-support.zip)
deploy:
  provider: releases
  api_key:
    secure: PU+u1AeYt+QA74997N3VV2FUv4Zyese9tXG76v7Jxo1FXJuN7KNc7c9T+Kt7iTic41hxT6PmqZz4u8LzokHU6F79qM663cIiLkkwff8uRxZCfvpLkRGU410EY9ykOznRFfAE0hRfXXLPW7VNPKOQfwfk8fEBhHhs/1NHQBkVTh5TwUWuKXGRGp3bVAYvRWc6ervblEhZjcvUWVY9dsexVMudMAhJky3tlXlsjGB9soSm5REzIE6OmyQk/ObIZuHhVUHMgqgkfxgzpsGlIXnOGQtEte9zaNPCzY37B+42V6bu6hTicy/oEUjapvfcT438x7KTVG3jaEJd1AuyvKIO57QKQP+FcAPl+prblszqs/gmFjOMb9UzmMGdpbSr9YpavzyWlC1M6jmkuZg1TLnNMAFLa2LXkggGKWN7SnLRHAroW9svoBZfXVIw//qA82Ps7gZ9tOveOX1aoItDbqo8MeD0Jn6R2adXBXPUN2buJ0HGB0lB8XoeuGiYxttt/U8x0jxg+qNgDfpM7k7zksZCKxvLBt1tJx4ndgqsomp8C1AWEWm39C/l+cJ3Alb13l5pw7vgXEr2E0PTywHEehrHRXnul0cd24dxaKqN3jON/5QNS8eX5kBEtENSM4u4M7MvtB66c98aLeNB226OtyKpU7GLtdxQp2s7dyk1Pum+m+8=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    php: 7.3
    repo: inc2734/snow-monkey-the-events-calendar-support
