dist: trusty
sudo: false
language: php
php:
- 7.2
- 7.3
env:
  global:
  - WP_VERSION=latest WP_MULTISITE=0
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
cache:
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
install:
- nvm install 8
- npm install
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- composer test
before_deploy:
- npm run zip
- ls -la snow-monkey-the-events-calendar-support.zip
- export RELEASE_FILE=$(ls snow-monkey-the-events-calendar-support.zip)
deploy:
  provider: releases
  api_key:
    secure: mydwSabhDo5HKKvGV8ATeWtYTrdJkA9m9XHFQ02uHFmIqUGU0jEG2wjbin4r0XLacOjNOQLtQGyMIFRAtvXt4Z4AxSEZdLu5zxg9KeKsH49CpOIA8kD/+lkKcv5NCWew/jHn6+9A3eqVOxBIF1nIFwzhCdkeKpZk6Pq53JMT7Gl0goHHet+V0+YPIqVfHoCa/GBkJBIwOD9xYnDNgunFQScmLwQzHmh8/8cKDprHhJtqScUImxhJHGKLcgpbUCZ+VKshTPJzMJeTCv2LqwLFM04aJcEQoIteLPrJFSD9wdGJm++4Q9HFJ+fXT8vTihgp7QlOXCaO2EjyZwmrxt5paHDhd7BEj/lYPLj1INBSVHTW/zPrv/lqFvJsEbVfg2Tvb3VFKAJh52QkO0q9rC9RlnnqgoeI+bNYhgujRdxI9p6gurZwHKZgqca7VWQ2Ill3kc+/lvggINlfU1cKUQjLondqTw9ViUSNXAIXOA5j8l1oo9KYWpWYW3vorSy+UaOFYAtjycCf24sYEnBa5q1R8DbNFyYRyrlMdOalsM8GicVvvmPWLlEr3HCliOlMaDqDs7I8M2R+CBQj/9ZtCj8UVflggZ4h0RHvCLtyd7ewLnWy7r4AZTX/BbfrCCa8kpMmqKbRJYpE8cO4hM7vhwU9ASa8ZsV9uBz6XXrIXcDXHEs=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    php: 7.3
    repo: inc2734/snow-monkey-the-events-calendar-support
